backend:
  name: github
  repo: allonsmandy/allonsmandy.netlify.com
  branch: master
  site_domain: allonsmandy.netlify.com

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "/assets/img"
logo_url: https://allonsmandy.netlify.app/static/6e6183de22fe514474366168d6de2a85/9dc27/avatar-2.jpg

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    description: "Posts do blog"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "off",
              "css",
              "js",
              "html",
              "devops",
              "frontend",
              "dev",
              "vue",
              "react",
              "git",
              "python",
              "dicas",
              "testes",
              "gulp",
              "mobile",
              "User Interface",
              "User Experience",
              "wordpress",
              "GraphQL",
              "dicas",
              "sass",
              "svelte",
              "Redes",
              "Engenharia de Software",
              "snippets",
              "leituras",
              "typescript",
            ],
        }
      - {
          label: "Background",
          name: "background",
          widget: "select",
          options:
            [
              { label: "Offtopic", value: "#989898" },
              { label: "CSS", value: "#3182bb" },
              { label: "Javascript", value: "#D6BA32" },
              { label: "HTML", value: "#EB7728" },
              { label: "Devops", value: "#B9D030" },
              { label: "Frontend", value: "#E6548F" },
              { label: "Dev", value: "#b49bf1" },
              { label: "Vue", value: "#50B883" },
              { label: "React", value: "#48acc7" },
              { label: "Git", value: "#EA4E32" },
              { label: "Python", value: "#F8D44C" },
              { label: "Dicas", value: "#a9aaaa" },
              { label: "Testes", value: "#bf975a" },
              { label: "Gulp", value: "#E1494F" },
              { label: "Mobile", value: "#9fbb68" },
              { label: "User Interface", value: "#D17E7B" },
              { label: "User Experience", value: "#a87bd1" },
              { label: "Wordpress", value: "#71AB13" },
              { label: "GraphQL", value: "#e663ab" },
              { label: "Dicas", value: "#32d6bf" },
              { label: "Sass", value: "#C76495" },
              { label: "Svelte", value: "#F34423" },
              { label: "Redes", value: "#1daafa" },
              { label: "Engenharia de sofware", value: "#caa6aa" },
              { label: "snippets", value: "#fff" },
              { label: "leituras", value: "#ffc" },
              { label: "typescript", value: "#007acc" },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "portfolio"
    label: "Portfólio"
    folder: "portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    description: "Portfolio"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "snippets"
    label: "Snippets"
    folder: "snippets"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    description: "Snippets de código"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Code", name: "code", widget: "code" }
